Repository Notliam99/TestingApi, pull requests merged in 2024-04, with the labels that each got.

#1 Pull Requuest - Feature implementation
  Cargo.toml
  src/main.rs
Labels: enhancement

#3 fixed and added a json path
  Cargo.toml
  src/main.rs
Labels: bug, enhancement

#4 specify port
  src/main.rs
Labels: enhancement

#7 documented main.rs, added actions
  .github/workflows/compileAndTest.yaml
  src/main.rs
Labels: documentation, enhancement

#8 Update README.md
  README.md
Labels: documentation

#9 Added cross-compile actions.
  .github/workflows/cross-compile.yaml
Labels: enhancement

#10 Logging
  Cargo.toml
  src/main.rs
Labels: enhancement

#11 Created a CODE_OF_CONDUCT.md
  CODE_OF_CONDUCT.md
Labels: documentation, enhancement

#13 issue templates
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
Labels: documentation, enhancement

#12 SECURITY.md
  SECURITY.md
Labels: documentation, enhancement

#14 Reworked most of the code into a library
  Cargo.toml
  src/args/mod.rs
  src/lib.rs
  src/main.rs
  src/paths/mod.rs
Labels: enhancement

#16 Fixes & New Path
  .github/workflows/cross-compile.yaml
  .gitignore
  src/args/mod.rs
  src/main.rs
  src/paths/mod.rs
Labels: enhancement, fix

#17 Update cross-compile.yaml
  .github/workflows/cross-compile.yaml
Labels: enhancement

#18 Update cross-compile.yaml
  .github/workflows/cross-compile.yaml
Labels: enhancement

#20 Path Unit Tests
  src/paths/mod.rs
  tests/path_test.rs
Labels: enhancement

#22 Piuro docs&check action change
  .github/workflows/compileAndTest.yaml
  README.md
  tests/path_test.rs
Labels: documentation, enhancement, fix

#26 Create releaseArtifacts.yaml
  .github/workflows/releaseArtifacts.yaml
Labels: enhancement

#27 docker image building next ill add the action
  .dockeriggnore
  .github/workflows/dockerBuild.yaml
  Dockerfile
Labels: enhancement

#29 Update releaseArtifacts.yaml
  .github/workflows/releaseArtifacts.yaml
Labels: fix

#32 Update result type.
  src/args/mod.rs
  src/main.rs
Labels: enhancement

#34 Image Optomiseation
  Dockerfile
  src/main.rs
Labels: enhancement, fix

#37 Kuberneties and Some Action Work
  .github/workflows/create_tag.yaml
  .github/workflows/dockerBuild.yaml
  README.md
  kuberneties/0-namespace.yaml
  kuberneties/1-deployment.yaml
  kuberneties/2-service.yaml
  kuberneties/3-ingress.yaml
  kuberneties/argo/argocd.yaml
Labels: enhancement, fix

#39 38 kuberneties action flawed
  .github/workflows/create_tag.yaml
  .github/workflows/create_tag_merge.yaml
Labels: bug, fix

#40 fix the action
  .github/workflows/create_tag_merge.yaml
Labels: bug

#41 Update create_tag_merge.yaml
  .github/workflows/create_tag_merge.yaml
Labels: bug, fix

#42 im soo silly next time use actionlint
  .github/workflows/create_tag.yaml
  .github/workflows/create_tag_merge.yaml
Labels: bug, fix

#44 Action hotfix
  .github/workflows/create_tag.yaml
Labels: bug, fix

#46 Action hotfix
  .github/workflows/create_tag.yaml
Labels: bug, fix

#48 Action hotfix
  .github/workflows/create_tag.yaml
Labels: bug, fix

#49 [Kuberneties Image Update]: (Tag) = v0.0.2
  kuberneties/1-deployment.yaml
Labels: enhancement, Automated Pull Request

#52 chanbge the the check to contains
  .github/workflows/create_tag_merge.yaml
Labels: bug, fix

#54 [Kuberneties Image Update]: (Tag) = v0.0.2
  kuberneties/1-deployment.yaml
Labels: enhancement, Automated Pull Request

#57 Action fix
  .github/workflows/create_tag.yaml
  .github/workflows/create_tag_merge.yaml
Labels: bug, fix

#58 [Kuberneties Image Update]: (Tag) = v0.0.2
  kuberneties/1-deployment.yaml
Labels: enhancement, Automated Image Update

#63 Action fix
  .github/workflows/create_tag_merge.yaml
Labels: bug, fix

#68 Action fix
  .github/workflows/create_tag_merge.yaml
Labels: fix

#69 [Kuberneties Image Update]: (Tag) = v0.0.2
  kuberneties/1-deployment.yaml
Labels: enhancement, Automated Image Update

#74 Action fix Syntax
  .github/workflows/create_tag_merge.yaml
Labels: bug, fix

#76 Action fix Syntax
  .github/workflows/create_tag_merge.yaml
Labels: bug, fix

#77 Action fix
  .github/workflows/create_tag_merge.yaml
Labels: bug, fix

#81 Action fix
  .github/workflows/create_tag_merge.yaml
Labels: bug, fix

#82 [Kuberneties Image Update]: (Tag) = v0.0.2
  kuberneties/1-deployment.yaml
Labels: enhancement, Automated Image Update

#83 github token replacement for auth
  .github/workflows/create_tag_merge.yaml
Labels: bug, fix

#84 Update 1-deployment.yaml
  kuberneties/1-deployment.yaml
Labels: fix

#85 [Kuberneties Image Update]: (Tag) = v0.0.2
  kuberneties/1-deployment.yaml
Labels: enhancement, Automated Image Update

#88 [Kuberneties Image Update]: (Tag) = v0.0.2
  kuberneties/1-deployment.yaml
Labels: enhancement, Automated Image Update

#89 update to the formating of the logging
  src/main.rs
Labels: enhancement

#93 Update create_tag_merge.yaml
  .github/workflows/create_tag_merge.yaml
Labels: fix

#91 Port Arg Fuction Rewrite
  src/args/mod.rs
  src/main.rs
Labels: enhancement

#95 Docker Platforms
  .github/workflows/create_tag_merge.yaml
  .github/workflows/dockerBuild.yaml
Labels: enhancement

#96 Update dockerBuild.yaml
  .github/workflows/dockerBuild.yaml
Labels: bug, fix

#97 Update README.md
  README.md
Labels: documentation, enhancement

#98 [Kuberneties Image Update]: (Tag) = v0.0.3
  kuberneties/1-deployment.yaml
Labels: enhancement, Automated Image Update

#99 Update README.md
  README.md
Labels: documentation

#100 added 404 service
  src/main.rs
  src/paths/mod.rs
Labels: enhancement
